/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 paris.gltf --transform
Author: PROXY (https://sketchfab.com/proxy000000000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/paris-saint-germain-x-jordan-home-stadium-kit-1d43be1db93143ea8cc35bb5fb339ad1
Title: Paris Saint-Germain x Jordan Home Stadium Kit
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/paris-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.02}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Default_OBJ} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.Default_OBJ} />
          </group>
          <mesh geometry={nodes.Object_7.geometry} material={materials['Default_OBJ.001']} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_9.geometry} material={materials['Default_OBJ.003']} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_11.geometry} material={materials['Default_OBJ.004']} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_13.geometry} material={materials['Default_OBJ.005']} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_15.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/paris-transformed.glb')
